// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfeShCSUnzTKSqgbZxPR3HNOhAe2PxRIQ',
    appId: '1:945570595529:web:14a132b7a3a89a54398318',
    messagingSenderId: '945570595529',
    projectId: 'paika-13250',
    authDomain: 'paika-13250.firebaseapp.com',
    storageBucket: 'paika-13250.firebasestorage.app',
    measurementId: 'G-L17WPKFG6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr_TEina-lkEJ4U_SgJKeYFIp2c2zEn6s',
    appId: '1:945570595529:android:d42f6c2b23775b17398318',
    messagingSenderId: '945570595529',
    projectId: 'paika-13250',
    storageBucket: 'paika-13250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALy4PwxFkA7RlRj3CBa69q7AjiAsJjeN0',
    appId: '1:945570595529:ios:903a1536a1feb6b1398318',
    messagingSenderId: '945570595529',
    projectId: 'paika-13250',
    storageBucket: 'paika-13250.firebasestorage.app',
    iosBundleId: 'com.vibeprojects.mahjongScorer',
  );
}
